name: Build Extension

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
      - name: Download Extension SDK Libs
        run: |
          mkdir -p lib
          curl -L https://github.com/mit-cml/extension-sdk/raw/master/lib/deps/deps.zip -o lib/deps.zip
          unzip lib/deps.zip -d lib/
          rm lib/deps.zip
      - name: Build with Ant
        run: ant